/**
 * @module src/systems/handler/character-creater-handler.js
 *
 * TSDoc autogenerated for character-creater-handler.js
 */

'use strict';

const Game = require('./game');
const { resolveInput } = require('../utils/input');
const { PLAYER } = require('../events/event-types');

const State = {
  CHOOSE_CLASS: 'choose-class',
  CONFIRM: 'confirm',
  DONE: 'done',
};

const { eventBus } = require('../events/event-bus').get();

/**
 * @param {import("../connections/connection")} connection
 * @param {import("../models/player").Player} player
 */
function create_character_handler(connection, player) {
  const stateHolder = {
    state: State.CHOOSE_CLASS,
  };

  const classOptions = {
    warrior: 'warrior',
    w: 'warrior',
    war: 'warrior',
    mage: 'mage',
    m: 'mage',
    mag: 'mage',
    rogue: 'rogue',
    r: 'rogue',
    rog: 'rogue',
  };

  const enter = () => {
    connection.socket.write('\nWelcome, new adventurer!\nChoose your class (warrior, mage, rogue): ');
  };

  const handle = (/** @type {string} */ input) => {
    const response = input.trim().toLowerCase();

    if (stateHolder.state === State.CHOOSE_CLASS) {
      const chosenClass = resolveInput(response, classOptions);

      if (!chosenClass) {
        connection.socket.write('Invalid class. Try warrior, mage, or rogue: ');
        return;
      }

      if (chosenClass === 'AMBIGUOUS') {
        connection.socket.write('Input is ambiguous. Please type more of the class name.\n');
        return;
      }

      player.class = chosenClass;

      stateHolder.state = State.CONFIRM;
      connection.socket.write('Character created! Press ENTER to begin your journey.\n');
      return;
    }

    if (stateHolder.state === State.CONFIRM) {
      initializePlayer(player);
      stateHolder.state = State.DONE;

      eventBus.emit(PLAYER.LOGGED_IN, { player, connection });
      connection.addHandler(new Game(connection, player));
    }
  };

  /**
   * @param {import("../models/player").Player} player
   */
  const initializePlayer = (player) => {
    player.level = 1;
    player.money = 0;
    player.room = '1';
  };

  const leave = () => {};
  const hungup = () => {
    console.log(`[Disconnected during character creation: ${player.name}]`);
  };

  return {
    enter,
    handle,
    leave,
    hungup,
  };
}

module.exports = { create_character_handler };
