/**
 * @module src/systems/handler/game-handler.js
 *
 * TSDoc autogenerated for game-handler.js
 */

'use strict';

const ConnectionHandler = require('../connections/connection-handler');
const { command_contexts } = require('../commands/command-contexts');
const { PLAYER } = require('../events/event-types');
const { eventBus } = require('../events/event-bus').get();

// Game Handler class
class Game extends ConnectionHandler {
  /**
   * @param {import("../connections/connection")} connection
   * @param {import("../models/player").Player} player
   */
  constructor(connection, player) {
    super(connection);
    this.player = player;
    this.handlePlayerInput = command_contexts;
  }

  enter() {
    eventBus.emit(PLAYER.ENTERED_REALM, { player: this.player });
  }

  /**
   * @param {string} input
   */
  handle(input) {
    this.handlePlayerInput(this.player, input);
  }

  leave() {
    eventBus.emit(PLAYER.LEFT_REALM, { player: this.player });
  }

  hungup() {
    eventBus.emit(PLAYER.LEFT_REALM, { player: this.player });
  }
}

module.exports = Game;
