/**
 * @module src/commands/store/sell.js
 *
 * TSDoc autogenerated for sell.js
 */

const error = require('debug')('mud:commands:store:sell:error');

const fuzzysort = require('fuzzysort');

const { send, dropItem } = require('../../functions/player');
const { redBold, cyanBold } = require('../../utils/formatting');
const { send_to_room } = require('../../functions/world');
const { roomRepository } = require('../../repository/repositories').get();

/**
 * @param {import('../../models/player').Player} player - The player issuing the command.
 * @param {string[]} args - The arguments passed to the command; expects item name as the first argument.
 */
module.exports = (player, [itemName]) => {
  if (!itemName) {
    send(player, redBold('What do you want to sell.'));
    return;
  }

  const room = roomRepository.get(player.room);
  if (!room) {
    error('Room not found in roomRepository for player: %O', player);
    send(player, redBold("There's no store here."));
    return;
  }

  const storeId = room.store;
  if (!storeId) {
    send(player, redBold("There's no store here."));
    return;
  }

  const matches = fuzzysort.go(itemName, player.inventory, {
    key: 'name',
    threshold: -1000, // optional: filter bad matches
  });

  if (matches.length === 0) {
    send(player, redBold("Sorry, you don't have that item!"));
    return;
  }

  if (matches.length > 1) {
    const options = matches.map((m, i) => `${i + 1}. ${m.obj.name}`).join('\n');
    send(player, redBold('Multiple matches found:\n') + options + '\nPlease be more specific.');
    return;
  }

  const item = matches[0].obj;

  dropItem(player, item);
  player.money += item.price;
  send_to_room(player, cyanBold(`${player.name} sells ${item.name}`));
};
