/**
 * @module src/commands/global/equip.js
 *
 * TSDoc autogenerated for equip.js
 */

const fuzzysort = require('fuzzysort');

const { send, useWeapon, useArmor } = require('../../functions/player');
const { redBold } = require('../../utils/formatting');
const { ItemType } = require('../../config');

/**
 *
 * @param {import('../../models/player').Player} player
 * @param {string[]} args
 * @returns
 */
module.exports = (player, args) => {
  const { playerRepository } = require('../../repository/repositories').get();

  if (!player.inventory) {
    send(player, redBold('You have nothing to equip!'));
  }

  const query = args.join(' ');
  const matches = fuzzysort.go(query, player.inventory, {
    key: 'name',
    threshold: -1000, // optional: filter bad matches
  });

  if (matches.length === 0) {
    send(player, redBold("You don't see that here!!"));
    return;
  }

  if (matches.length > 1) {
    const options = matches.map((m, i) => `${i + 1}. ${m.obj.name}`).join('\n');
    send(player, redBold('Multiple matches found:\n') + options + '\nPlease be more specific.');
    return;
  }

  const item = matches[0].obj;
  if (item.type === ItemType.ARMOR) {
    useArmor(player, item);
  } else if (item.type === ItemType.WEAPON) {
    useWeapon(player, item);
  } else {
    send(player, redBold(`${item.name} isn't a weapon or armor`));
    return;
  }

  send(player, `You equip ${item.name}`);
  playerRepository.save(player.id);
};
