/**
 * @module src/commands/global/experience.js
 *
 * TSDoc autogenerated for experience.js
 */

const { send, needForLevel } = require('../../functions/player');
const { printSection } = require('../../utils/formatting');

/**
 *
 * @param {import('../../models/player').Player} player
 * @returns
 */
module.exports = (player) => {
  const nextXP = needForLevel(player, player.level + 1);
  const percent = Math.round((100 * player.experience) / nextXP);

  const experience = ['Level: ' + player.level, 'Experience:' + `${player.experience}/${nextXP} (${percent}%)`];
  send(player, printSection('Your Experience', experience));
};
