/**
 * @module src/commands/global/get.js
 *
 * TSDoc autogenerated for get.js
 */

const fuzzysort = require('fuzzysort');

const { redBold } = require('../../utils/formatting');
const { send } = require('../../functions/player');
const { PLAYER } = require('../../events/event-types');

/**
 *
 * @param {import('../../models/player').Player} player
 * @param {string[]} args
 * @returns
 */
module.exports = (player, args) => {
  const { roomRepository } = require('../../repository/repositories').get();
  const { eventBus } = require('../../events/event-bus').get();

  const room = roomRepository.get(player.room);

  if (!room?.items) {
    send(player, redBold("There's nothing here to pickup!"));
    return;
  }

  const query = args.join(' ');
  const matches = fuzzysort.go(query, room.items, {
    key: 'name',
    threshold: -1000, // optional: filter bad matches
  });

  if (matches.length === 0) {
    send(player, redBold("You don't see that here!!"));
    return;
  }

  if (matches.length > 1) {
    const options = matches.map((m, i) => `${i + 1}. ${m.obj.name}`).join('\n');
    send(player, redBold('Multiple matches found:\n') + options + '\nPlease be more specific.');
    return;
  }

  const item = matches[0].obj;
  eventBus.emit(PLAYER.ITEM_PICKED_UP, { player, item, room, source: 'room' });
};
