/**
 * @module src/commands/global/get.js
 *
 * TSDoc autogenerated for get.js
 */

const _ = require('lodash');
const Fuse = require('fuse.js');

const { redBold } = require('../../utils/formatting');
const { send } = require('../../functions/player');

/**
 *
 * @param {import('../../models/player').Player} player
 * @param {string[]} args
 * @returns
 */
module.exports = (player, args) => {
  const { roomRepository } = require('../../repository/repositories').get();
  const { eventBus } = require('../../events/event-bus').get();

  const room = roomRepository.get(player.room);

  if (!room?.items) {
    send(player, redBold("There's nothing here to pickup!"));
  }

  // @ts-ignore
  const fuse = new Fuse(room.items, {
    keys: ['name'],
    threshold: 0.4,
  });

  const matches = fuse.search(args.join(' '));
  if (matches.length === 0) {
    send(player, redBold("You don't see that here!!"));
    return;
  }

  if (matches.length > 1) {
    const options = matches.map((m, i) => `  ${i + 1}. ${m.item.name}`).join('\n');
    send(player, redBold('Multiple matches found:\n') + options + '\nPlease be more specific.');
    return;
  }

  const item = _.first(matches).item;
  eventBus.emit('player.item.picked_up', { player, item, room, source: 'room' });
};
