/**
 * @module src/commands/global/look.js
 *
 * TSDoc autogenerated for look.js
 */

const { send } = require('../../functions/player');
const { render_room } = require('../../functions/room');

/**
 *
 * @param {import('../../models/player').Player} player
 * @returns
 */
module.exports = (player) => {
  send(player, render_room(player.room));
};
