/**
 * @module src/commands/global/quit.js
 *
 * TSDoc autogenerated for quit.js
 */

const { send_to_everyone } = require('../../functions/world');
const { yellowBold } = require('../../utils/formatting');

const { playerRepository, connectionRepository } = require('../../repository/repositories').get();

/**
 *
 * @param {import('../../models/player').Player} player
 * @returns
 */
module.exports = (player) => {
  playerRepository.delete(player.id);

  const connection = connectionRepository.getConnection(player.id);
  connection.close();

  send_to_everyone(yellowBold(`${player.name} has left the realm.`));
};
