/**
 * @module src/commands/command-router.js
 *
 * TSDoc autogenerated for command-router.js
 */

const path = require('path');
const fs = require('fs');
const fuzzysort = require('fuzzysort');
const commandsLog = require('debug')('mud:command:router:getAllCommands');
const routeLog = require('debug')('mud:command:router:route_command');

const { is_direction, get_command_function } = require('./movement/movement-alias');
const { send } = require('../functions/player');

const commandCache = new Map();

/**
 * Scans the `src/commands` directory to retrieve all available command context folders.
 *
 * @returns {string[]} Array of command context folder names.
 */
const getCommandContexts = () => {
  const base = path.join(process.cwd(), 'src/commands');
  const dirs = fs.readdirSync(base).filter((f) => fs.statSync(path.join(base, f)).isDirectory());
  commandsLog(`[getCommandContexts] Found contexts: ${dirs.join(', ')}`);
  return dirs;
};

/**
 * Loads all available commands based on the provided contexts.
 * Uses in-memory caching unless `reload` is set to true.
 *
 * @param {string[]} contexts - List of context folder names to load commands from.
 * @param {{ reload?: boolean }} [options={}] - Options object to force reload.
 * @returns {Array<{ verb: string, ctx: string, file: string }>} Array of command definitions.
 */
const getAllCommands = (contexts, { reload = false } = {}) => {
  const activeContexts = contexts?.length ? contexts : getCommandContexts();
  const cacheKey = activeContexts.sort().join(',');

  if (!reload && commandCache.has(cacheKey)) {
    commandsLog(`Using cached commands for contexts: ${cacheKey}`);
    return commandCache.get(cacheKey);
  }

  commandsLog(`Loading commands for contexts: ${cacheKey}`);

  const allCommands = activeContexts.flatMap((ctx) => {
    const dir = path.join(process.cwd(), 'src/commands', ctx);
    commandsLog(`Searching directory: ${dir}`);

    if (!fs.existsSync(dir)) {
      commandsLog(`Directory does not exist: ${dir}`);
      return [];
    }

    const files = fs.readdirSync(dir).filter((file) => file.endsWith('.js'));
    commandsLog(`Found ${files.length} command(s) in '${ctx}':`, files);

    return files.map((file) => ({
      verb: path.basename(file, '.js'),
      ctx,
      file: path.join(dir, file),
    }));
  });

  commandCache.set(cacheKey, allCommands);
  return allCommands;
};

/**
 * Routes a command to the correct implementation file.
 * Supports direction commands and fuzzy matching for unrecognized inputs.
 *
 * @param {string[]} contexts - Active command contexts to search within.
 * @param {string} verb - The command verb typed by the player.
 * @param {string[]} args - Arguments passed with the command.
 * @param {import('../models/player').Player} player - The player executing the command.
 * @param {{ reload?: boolean }} [options={}] - Optional routing configuration (e.g., reload).
 * @returns {any} The return value of the routed command function.
 */
const route_command = (contexts, verb, args, player, options = {}) => {
  routeLog(`Player: ${player.name}, Verb: ${verb}, Args: ${args.join(' ')}`);

  const commands = getAllCommands(contexts, options);

  if (options.reload) {
    routeLog(`Reload mode active, skipping execution.`);
    return;
  }

  if (is_direction(verb)) {
    const file = get_command_function(verb);
    routeLog(`Recognized direction command: ${verb} -> ${file}`);
    if (file) {
      delete require.cache[require.resolve(file)];
      const fn = require(file);
      return fn(player, args);
    }
  }

  const command = commands.find((c) => c.verb === verb || c.verb.startsWith(verb));

  if (command) {
    routeLog(`Matched command: ${command.verb} in ${command.ctx}`);
    delete require.cache[require.resolve(command.file)];
    const fn = require(command.file);
    return fn(player, args, { route_command });
  }

  const matches = fuzzysort.go(verb, commands, {
    key: 'name',
    threshold: -1000, // optional: filter bad matches
  });
  const suggestion = matches[0]?.obj?.verb;

  if (suggestion) {
    routeLog(`Unknown command: '${verb}', suggested: '${suggestion}'`);
    return send(player, `Unknown command: '${verb}'. Did you mean '${suggestion}'?`);
  }

  routeLog(`Unknown command with no suggestion: '${verb}'`);
  send(player, `Unknown command: '${verb}'`);
};

module.exports = { route_command };
