/**
 * @module src/functions/mob/create-mob.js
 *
 * TSDoc autogenerated for create-mob.js
 */

'use strict';

const _ = require('lodash');
const mob_model = require('../../models/mob');

/**
 * @typedef {import('../../models/mob')} Mob
 */

/**
 * Creates a new mob object by cloning the base mob model and applying provided overrides.
 *
 * @param {Partial<Mob>} [data={}] - Partial data to override the default mob model.
 * @param {string} [room] - roomo id
 * @returns {Mob} The initialized mob object with helper methods.
 */
function create_mob(data = {}, room) {
  const mob = _.cloneDeep(mob_model);

  // Populate with values or defaults
  Object.assign(mob, data);

  mob.room = room;
  mob.hp = data.maxHp;
  mob.nextAttackTime = data.nextAttackTime || 0;

  return mob;
}

module.exports = {
  create_mob,
};
