/**
 * @module src/config/index.js
 *
 * TSDoc autogenerated for index.js
 */

'use strict';

/**
 * @readonly
 * @enum {string}
 */
const ItemType = {
  WEAPON: 'WEAPON',
  ARMOR: 'ARMOR',
  TOKEN: 'TOKEN',
};

/**
 * @readonly
 * @enum {string}
 */
const PlayerRank = {
  REGULAR: 'REGULAR',
  GOD: 'GOD',
  ADMIN: 'ADMIN',
};

/**
 * @readonly
 * @enum {string}
 */
const RoomType = {
  PLAIN_ROOM: 'PLAINROOM',
  STORE: 'STORE',
};

/**
 * @readonly
 * @enum {string}
 */
const Direction = {
  NORTH: 'NORTH',
  EAST: 'EAST',
  SOUTH: 'SOUIH',
  WEST: 'SOUIH',
};

/**
 * @readonly
 * @enum {string}
 */
const ActorType = {
  PLAYER: 'PLAYER',
  NPC: 'NPC',
  MOB: 'MOB',
};

const AttackResult = {
  HIT: 'HIT',
  MISS: 'MISS',
};

const STATBAR_INTERVAL_MS = 5000;
const SPAWN_COOLDOWN = 60 * 1000;

module.exports = {
  ItemType,
  PlayerRank,
  RoomType,
  Direction,
  ActorType,
  AttackResult,
  STATBAR_INTERVAL_MS,
  SPAWN_COOLDOWN,
};
