/**
 * @module src/commands/admin/reload.js
 *
 * TSDoc autogenerated for reload.js
 */

const { green, redBold } = require('../../utils/formatting');
const { send } = require('../../functions/player');

/**
 *
 * @param {import('../../models/player').Player} player
 * @param {string[]} args
 * @param {{ dispatchCommand: Function }} options - Optional context with dispatchCommand used to reload commands.
 */
module.exports = (player, args, { dispatchCommand }) => {
  try {
    dispatchCommand([], '', [], player, { reload: true });
    send(player, green('Command cache reloaded from disk.'));
  } catch (err) {
    console.error('[reload] failed to reload commands:', err);
    send(player, redBold('Failed to reload commands.'));
  }
};
