/**
 * @module src/events/player-events.js
 *
 * TSDoc autogenerated for player-events.js
 */

'use strict';

/**
 * @module systems/player-events
 *
 * Handles lifecycle events related to players such as entering the realm,
 * logging in, or leaving the world.
 */

const info = require('debug')('mud:player:player-events');
const error = require('debug')('mud:player:player-events:error');

const { send_to, send_announcement, send_to_room } = require('../functions/world');
const { cyan, yellowBold, redBold, cyanBold, greenBold } = require('../utils/formatting');
const { send, needForNextLevel } = require('../functions/player');

const { PLAYER } = require('./event-types');

/**
 * Registers player-related event listeners onto the global event bus.
 */
const register_player_events = () => {
  const { eventBus } = require('./event-bus').get();
  const { connectionRepository, roomRepository, playerRepository } = require('../repository/repositories').get();

  /**
   *
   * @param {import('./event-types').PlayerEvent} param0
   */
  eventBus.on(PLAYER.ENTERED_REALM, ({ player }) => {
    const connection = connectionRepository.getConnection(player.id);
    if (!connection) {
      error('%s has no connection', player.id);
      return;
    }
    send_announcement(cyan(`${player.name} appears in the realm.`));

    const room = roomRepository.get(player.room);
    if (!room) {
      error('player [%s] event [%s] from room [%s] that does not exist', player.id, PLAYER.ENTERED_REALM, player.room);
      eventBus.emit(PLAYER.MOVED, { player, to: '1' });
    } else {
      eventBus.emit(PLAYER.ENTERED_ROOM, { player, to: player.room });
    }
  });

  /**
   *
   * @param {import('./event-types').PlayerEvent} param0
   */
  eventBus.on(PLAYER.LEFT_REALM, ({ player }) => {
    send_to(player, yellowBold(`${player.name} vanishes into the void.`));
  });

  /**
   *
   * @param {import('./event-types').PlayerEvent} param0
   */
  eventBus.on(PLAYER.LOGGED_IN, ({ player }) => {
    send_to(player, yellowBold(`${player.name} has entered the realm.`));
  });

  /**
   *
   * @param {import('./event-types').PlayerMoveEvent} param0
   */
  eventBus.on(PLAYER.MOVED, ({ player, direction, from, to, enteredFrom }) => {
    const nextRoom = roomRepository.get(to);
    if (!nextRoom) {
      error('trying to move player to missing room %s', to);
      return;
    }

    // Update player room
    player.room = to;

    // Remove from current room
    eventBus.emit(PLAYER.LEFT_ROOM, { player, from, direction });
    eventBus.emit(PLAYER.ENTERED_ROOM, { player, to, enteredFrom });
  });

  /**
   *
   * @param {import('./event-types').PlayerDiedEvent} param0
   */
  eventBus.on(PLAYER.DIED, ({ player, attacker }) => {
    send_to_room(player, `${cyanBold(player.name)} has been defeated by ${redBold(attacker.name)}!`);

    player.setHitPoints(Math.floor(player.maxHp * 0.7));
    player.room = 1;

    send(player, yellowBold(`You have died, but have been ressurected`));
    eventBus.emit(PLAYER.ENTERED_ROOM, { player, to: player.room });
  });

  eventBus.on(PLAYER.XP_GAINED, ({ player, amount }) => {
    player.experience += amount;

    send(player, cyanBold(`You gain ${amount} experience.`));

    const required = needForNextLevel(player);
    if (player.experience >= required) {
      player.level += 1;
      player.experience -= required;

      eventBus.emit(PLAYER.LEVEL_UP, { player });
    }
    playerRepository.save(player.id);
  });

  /**
   *
   * @param {import('./event-types').PlayerEvent} param0
   */
  eventBus.on(PLAYER.LEVEL_UP, ({ player }) => {
    player.maxHp += 10 * player.level;
    player.hp = player.maxHp;

    send(player, greenBold(`You have reached level ${player.level}!`));
    send(player, cyanBold(`Your max HP is now ${player.maxHp}.`));

    info(`${player.name} leveled up to ${player.level}`);
  });
};

module.exports = { register_player_events };
