/**
 * @module src/functions/combat/auto-attack.js
 *
 * TSDoc autogenerated for auto-attack.js
 *
 * @typedef {import('../../models/mob').Mob} Mob
 * @typedef {import('../../models/player').Player} Player
 */

const { resolveAttack } = require('./resolve-attack');
const { is_alive } = require('../world');

/**
 *
 * @param {Player|Mob} attacker
 * @param {Player|Mob} target
 * @param {number} timeNow
 * @returns
 */
const perform_auto_attack = (attacker, target, timeNow) => {
  if (!is_alive(attacker) || !is_alive(target)) return;

  const attackSpeed = attacker.weapon?.speed || 1000;

  resolveAttack(attacker, target);
  attacker.nextAttackTime = timeNow + attackSpeed;
};

module.exports = {
  perform_auto_attack,
};
