/**
 * @module src/functions/combat/damage.js
 *
 * TSDoc autogenerated for damage.js
 *
 * @typedef {import('../../models/enemy').Enemy} Enemy
 * @typedef {import('../../models/player').Player} Player
 */

const _ = require('lodash');
const { ActorType } = require('../../config');

/**
 *
 * @param {Player|Enemy} attacker
 * @param {Player|Enemy} target
 * @returns {number} base damage
 */
// eslint-disable-next-line no-unused-vars
const calculateDamage = (attacker, target) => {
  if (attacker.type === ActorType.PLAYER) return 100;

  const weapon = attacker.weapon;
  const baseMin = weapon?.min || 1;
  const baseMax = weapon?.max || 4;

  const baseDamage = _.random(baseMin, baseMax);

  //   const strengthMod = Math.floor((attacker.strength || 0) * 0.5);
  //   const defense = target.defense || 0;
  //   const totalDamage = Math.max(baseDamage + strengthMod - defense, 0);
  return baseDamage;
};

module.exports = {
  calculateDamage,
};
