/**
 * @module src/functions/combat/messages.js
 *
 * TSDoc autogenerated for messages.js
 *
 * @typedef {import('../../models/enemy').Enemy} Enemy
 * @typedef {import('../../models/player').Player} Player
 */

const { AttackResult } = require('../../config');
const { yellow, redBold } = require('../../utils/formatting');
const { send_to_room } = require('../world');

/**
 *
 * @param {Player|Enemy} attacker
 * @param {Player|Enemy} target
 * @param {{ type: string, damage?: number }} result - The result of the attack, including type (HIT or MISS) and optional damage.
 *
 * @returns {void}
 */
const sendCombatMessage = (attacker, target, result) => {
  const { type, damage } = result;

  if (type === AttackResult.MISS) {
    send_to_room(attacker, `${yellow(attacker.name)} swings at ${yellow(target.name)} but ${redBold('misses')}.`);
    return;
  }

  if (type === AttackResult.HIT) {
    send_to_room(attacker, `${yellow(attacker.name)} hits ${yellow(target.name)} for ${redBold(damage)} damage.`);
    return;
  }
};

module.exports = {
  sendCombatMessage,
};
